language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t pbuczma/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true pbuczma/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react"
  env: "Docker-react-env"
  bucket_name: ""
  backet_path: "docker-react"
  on:
    branch: main
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
 
